import '../styles/globals.css'
import Head from 'next/head'
import React from 'react'

function MyApp({ Component, pageProps }) {
  return <>
      <Head>
        <title>My-top app</title>
        <meta name="description" content="Generated by create next app" />
        <link key={1} rel="icon" href="/favicon.ico" />
      </Head>

    <Component {...pageProps} />
    </>
}

export default MyApp
